[general]
import = ["~/.config/alacritty/theme.toml"]

[font]
normal.family = "0xProto Nerd Font"
size = 10
[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "Enter", mods = "Super", action = "SpawnNewInstance"}
]
